# Generated by Django 5.2.10 on 2026-02-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrecord",
            name="bullets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="longest_sentence",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="overused",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="passive_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="ttr",
            field=models.FloatField(default=0.0),
        ),
    ]
